
export const countryToCurrency: { [key: string]: string } = {
    "Afghanistan": "AFN",
    "Albania": "EUR",
    "Algeria": "DZD",
    "Argentina": "ARS",
    "Australia": "AUD",
    "Austria": "EUR",
    "Bahrain": "BHD",
    "Bangladesh": "BDT",
    "Belgium": "EUR",
    "Benin": "XOF",
    "Bhutan": "BTN",
    "Botswana": "BWP",
    "Brazil": "BRL",
    "Bulgaria": "BGN",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Cambodia": "KHR",
    "Cameroon": "XAF",
    "Canada": "CAD",
    "Cape Verde": "CVE",
    "Central African Republic": "XAF",
    "Chad": "XAF",
    "Chile": "CLP",
    "China": "CNY",
    "Colombia": "COP",
    "Comoros": "KMF",
    "Congo": "XAF",
    "Croatia": "HRK",
    "Czech Republic": "CZK",
    "Democratic Republic of the Congo": "CDF",
    "Denmark": "DKK",
    "Djibouti": "DJF",
    "Egypt": "EGP",
    "Equatorial Guinea": "XAF",
    "Eritrea": "ERN",
    "Estonia": "EUR",
    "Ethiopia": "ETB",
    "Eswatini": "SZL",
    "Finland": "EUR",
    "France": "EUR",
    "Gabon": "XAF",
    "Gambia": "GMD",
    "Germany": "EUR",
    "Ghana": "GHS",
    "Greece": "EUR",
    "Guinea": "GNF",
    "Guinea-Bissau": "XOF",
    "Hong Kong": "HKD",
    "Hungary": "HUF",
    "Iceland": "ISK",
    "India": "INR",
    "Indonesia": "IDR",
    "Iran": "IRR",
    "Iraq": "IQD",
    "Ireland": "EUR",
    "Israel": "ILS",
    "Italy": "EUR",
    "Ivory Coast": "XOF",
    "Japan": "JPY",
    "Jordan": "JOD",
    "Kazakhstan": "KZT",
    "Kenya": "KES",
    "Kuwait": "KWD",
    "Kyrgyzstan": "KGS",
    "Laos": "LAK",
    "Latvia": "EUR",
    "Lebanon": "LBP",
    "Lesotho": "LSL",
    "Liberia": "LRD",
    "Libya": "LYD",
    "Lithuania": "EUR",
    "Luxembourg": "EUR",
    "Madagascar": "MGA",
    "Malawi": "MWK",
    "Malaysia": "MYR",
    "Maldives": "MVR",
    "Mali": "XOF",
    "Mauritania": "MRU",
    "Mauritius": "MUR",
    "Mexico": "MXN",
    "Mongolia": "MNT",
    "Morocco": "MAD",
    "Mozambique": "MZN",
    "Myanmar": "MMK",
    "Namibia": "NAD",
    "Nepal": "NPR",
    "Netherlands": "EUR",
    "New Zealand": "NZD",
    "Niger": "XOF",
    "Nigeria": "NGN",
    "North Korea": "KPW",
    "Norway": "NOK",
    "Oman": "OMR",
    "Pakistan": "PKR",
    "Peru": "PEN",
    "Philippines": "PHP",
    "Poland": "PLN",
    "Portugal": "EUR",
    "Qatar": "QAR",
    "Republic of the Congo": "XAF",
    "Romania": "RON",
    "Russia": "RUB",
    "Rwanda": "RWF",
    "São Tomé and Príncipe": "STN",
    "Saudi Arabia": "SAR",
    "Senegal": "XOF",
    "Serbia": "RSD",
    "Seychelles": "SCR",
    "Sierra Leone": "SLL",
    "Singapore": "SGD",
    "Slovakia": "EUR",
    "Slovenia": "EUR",
    "Somalia": "SOS",
    "South Africa": "ZAR",
    "South Korea": "KRW",
    "Spain": "EUR",
    "Sri Lanka": "LKR",
    "Sudan": "SDG",
    "Sweden": "SEK",
    "Switzerland": "CHF",
    "Syria": "SYP",
    "Tanzania": "TZS",
    "Thailand": "THB",
    "Togo": "XOF",
    "Tunisia": "TND",
    "Turkey": "TRY",
    "Uganda": "UGX",
    "Ukraine": "UAH",
    "United Arab Emirates": "AED",
    "United Kingdom": "GBP",
    "United States": "USD",
    "Uruguay": "UYU",
    "Uzbekistan": "UZS",
    "Vietnam": "VND",
    "Yemen": "YER",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL",
};

export const getCurrencyByCountry = (country: string): string | undefined => {
    return countryToCurrency[country];
};

export const getAllCountries = (): string[] => {
    return Object.keys(countryToCurrency).sort();
};
