/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  safelist: [
    'bg-weconnect-red',
    'text-weconnect-red',
    'border-weconnect-red',
    'bg-weconnect-black',
    'text-weconnect-black',
    'border-weconnect-black',
    'bg-brand-blue',
    'text-brand-blue',
    'border-brand-blue',
    'bg-brand-orange',
    'text-brand-orange',
    'border-brand-orange',
    'bg-brand-green',
    'text-brand-green',
    'border-brand-green',
    'bg-brand-purple',
    'text-brand-purple',
    'border-brand-purple',
    'bg-brand-cyan',
    'text-brand-cyan',
    'border-brand-cyan',
    'hover:bg-weconnect-red',
    'focus:ring-red-400',
    'focus:border-brand-blue',
  ],
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      fontFamily: {
        sans: [
          "Proxima Nova",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "Cantarell",
          "Fira Sans",
          "Droid Sans",
          "Helvetica Neue",
          "sans-serif",
        ],
        proxima: ["Proxima Nova", "sans-serif"],
      },
      colors: {
        // WeConnect Primary Brand Colors (from moodboard)
        weconnect: {
          red: '#EF444E',
          black: '#2B2C2B',
        },
        // Secondary Color Palette (from moodboard)
        brand: {
          blue: '#446AEF',
          orange: '#F7B638',
          green: '#5ED790',
          purple: '#AC5ADE',
          cyan: '#63DCE4',
        },
      },
      spacing: {
        // Grid system based on 30px columns
        'grid': '30px',
        'grid-2': '60px',
        'grid-3': '90px',
        'grid-4': '120px',
        'grid-5': '150px',
        'grid-6': '180px',
        'grid-half': '15px',
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '0.875rem', // Optimized for smaller screens
        'lg': '1rem',
        'xl': '1.125rem',
        '2xl': '1.25rem',
      },
      maxWidth: {
        'grid': '30px',
        'grid-2': '60px',
        'grid-3': '90px',
        'grid-4': '120px',
        'grid-5': '150px',
        'grid-6': '180px',
        'grid-8': '240px',
        'grid-10': '300px',
        'grid-12': '360px',
      },
    },
  },
  plugins: [],
};
